parse_config:
  # Add any ZMK-specific preamble here if needed
  zmk_preamble: "#include <zmk-helpers/key-labels/34.h>"
  zmk_additional_includes:
    - "modules/helpers/include"

draw_config:
  footer_text: "zmk-config"
  dark_mode: auto 